-- CREATE USER [SuitAlterationManagerUser] FOR LOGIN [SuitAlterationManagerUser] WITH DEFAULT_SCHEMA=[dbo]
-- GO
-- sys.sp_addrolemember @rolename = N'db_owner', @membername = N'SuitAlterationManagerUser'
-- GO